import { Account } from "./account/index.js";
import { Achievements } from "./achievements/index.js";
import { Backstory } from "./backstory/index.js";
import { build } from "./build/index.js";
import { Characters } from "./characters/index.js";
import { colors } from "./colors/index.js";
import { Commerce } from "./commerce/index.js";
import { continents } from "./continents/index.js";
import { createsubtoken } from "./createsubtoken/index.js";
import { currencies } from "./currencies/index.js";
import { dailycrafting } from "./dailycrafting/index.js";
import { dungeons } from "./dungeons/index.js";
import { Emblem } from "./emblem/index.js";
import { emotes } from "./emotes/index.js";
import { files } from "./files/index.js";
import { finishers } from "./finishers/index.js";
import { gliders } from "./gliders/index.js";
import { Guild } from "./guild/index.js";
import { Home } from "./home/index.js";
import { items } from "./items/index.js";
import { itemstats } from "./itemstats/index.js";
import { jadebots } from "./jadebots/index.js";
import { legendaryarmory } from "./legendaryarmory/index.js";
import { legends } from "./legends/index.js";
import { mailcarriers } from "./mailcarriers/index.js";
import { mapchests } from "./mapchests/index.js";
import { maps } from "./maps/index.js";
import { masteries } from "./masteries/index.js";
import { materials } from "./materials/index.js";
import { minis } from "./minis/index.js";
import { Mounts } from "./mounts/index.js";
import { novelties } from "./novelties/index.js";
import { outfits } from "./outfits/index.js";
import { pets } from "./pets/index.js";
import { professions } from "./professions/index.js";
import { Pvp } from "./pvp/index.js";
import { quaggans } from "./quaggans/index.js";
import { quests } from "./quests/index.js";
import { races } from "./races/index.js";
import { raids } from "./raids/index.js";
import { Recipes } from "./recipes/index.js";
import { skiffs } from "./skiffs/index.js";
import { skills } from "./skills/index.js";
import { specializations } from "./specializations/index.js";
import { Stories } from "./stories/index.js";
import { titles } from "./titles/index.js";
import { tokeninfo } from "./tokeninfo/index.js";
import { traits } from "./traits/index.js";
import { worldbosses } from "./worldbosses/index.js";
import { worlds } from "./worlds/index.js";
import { Wvw } from "./wvw/index.js";

export class V2 {
  account: Account = new Account();
  achievements: Achievements = new Achievements();
  backstory: Backstory = new Backstory();
  build = build;
  characters: Characters = new Characters();
  colors = colors;
  commerce: Commerce = new Commerce();
  continents = continents;
  createsubtoken = createsubtoken;
  currencies = currencies;
  dailycrafting = dailycrafting;
  dungeons = dungeons;
  emblem: Emblem = new Emblem();
  emotes = emotes;
  files = files;
  finishers = finishers;
  gliders = gliders;
  guild: Guild = new Guild();
  home: Home = new Home();
  items = items;
  itemstats = itemstats;
  jadebots = jadebots;
  legendaryarmory = legendaryarmory;
  legends = legends;
  mailcarriers = mailcarriers;
  mapchests = mapchests;
  maps = maps;
  masteries = masteries;
  materials = materials;
  minis = minis;
  mounts: Mounts = new Mounts();
  novelties = novelties;
  outfits = outfits;
  pets = pets;
  professions = professions;
  pvp: Pvp = new Pvp();
  quaggans = quaggans;
  quests = quests;
  races = races;
  raids = raids;
  recipes: Recipes = new Recipes();
  skiffs = skiffs;
  skills = skills;
  specializations = specializations;
  stories: Stories = new Stories();
  titles = titles;
  tokeninfo = tokeninfo;
  traits = traits;
  worldbosses = worldbosses;
  worlds = worlds;
  wvw: Wvw = new Wvw();
}

